### ISSUE TITLE
HTML/CSS - header dropdown for sandbox button and pills for nav active and hover states

### ISSUE THREAD

**Issue by salus-sage** [janastu/ncbs-omeka-backbone-client#1]
same for the navigation items in the footer. specs in design folder

**Comment by khushpreet-kaur** [comment]
Hover state for footer nav is done with the following: 
1. Highlight 'ncbs-nav-footer panel-footer' div with light colored font. 
2. Removed underline from footer links on hover.

**Comment by salus-sage** [comment]
@khushpreet-kaur guess this issue can be closed.
