### ISSUE TITLE
Peopleplex and Timeline: Images not loading

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#112]
The images do not load in Peopleplex and Timeline. Using Chrome. Same issue noticed in Firefox.
Using latest versions for both.

**Comment by pradyumnat** [comment]
@vns2  Please check now. Images are loading.

**Comment by pradyumnat** [comment]
Moved images files of timeline and peopleplex from ncbs25dev to ncbs25live server in their respective folders in sandbox. Updated code to reflect the same.

**Comment by salus-sage** [comment]
issue resolved
