### ISSUE TITLE
For the Picture slide shows, the slider arrows can appear on the images instead of on the bottom of the image.

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#14]

**Comment by salus-sage** [comment]
@khushpreet-kaur can you look into this? solution may include css. refer to imageviewer documentation to see if you can achive similar effect insteadof bootstrap glyphs

**Comment by khushpreet-kaur** [comment]
@salus-sage  Issue is fixed now.  I'm using 'bootstrap glyphs' as per the design requirement.  Please check.

**Comment by salus-sage** [comment]
increase the arrow size to 24px - and merge the change with master

**Comment by khushpreet-kaur** [comment]
Fixed.
