### ISSUE TITLE
video not playing. Says video with no mimetype supported

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#21]

**Comment by salus-sage** [comment]
@pradyumnat can you look at the html5 video and audio tag requirements and see if we comply with the files we are using?

**Comment by pradyumnat** [comment]
Need help to identify which videos give this error with which browser.

**Comment by salus-sage** [comment]
unable to recreate this issue,
 all videos are loading fine, verified network - issue resolved
