### ISSUE TITLE
go to top link required on every page.

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#27]

**Comment by salus-sage** [comment]
Need to see if we can accommodate this enhancement in this milestone. if not will add to next milestone. was not part of design requirements. @vns2

**Comment by vns2** [comment]
Yes, I see your point and it will be nice if it is there. But sure, it can come after this release.

**Comment by salus-sage** [comment]
Solution - Go to top of the page to switch between chapters and Go to bottomm of the page to switch between themes
Issue resolved - icons is bottom right hand corner of all pages. screen shot attached
![screenshot 18](https://cloud.githubusercontent.com/assets/6399323/20520135/a204f108-b0cb-11e6-87fd-8a3d8dd0477c.png)
