### ISSUE TITLE
hiring -  Video sound very low at full volume also. - last six audio are opening in new tab

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#31]

**Comment by salus-sage** [comment]
need to check the volume with the original video.  @shalinia can you please assign this issue to somebody from the content production team to check the sound in original video and the web version and see if anything can be done to resolve this issue.

**Comment by salus-sage** [comment]
Video sound very low at full volume also - original video might have problem -  unable to find a solution unless the source is replaced.
last six audio are opening in new tab - resolved by creating collapsible  gallery

**Comment by salus-sage** [comment]
The video sound with low volume is out of scope for us to work, client needs to replace the source file. closing this issue as resolved.
