### ISSUE TITLE
All themes: Single Photo: Footer edit: Remove "1/1" for single photos

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#34]
![1-8_p1_footer_remove-1of1](https://cloud.githubusercontent.com/assets/4581081/19718590/9a393f0e-9b83-11e6-9e51-585801d34d06.png)

**Comment by salus-sage** [comment]
@khushpreet-kaur assigning this issue to you, solution is similar to what we did to remove the arrows for 1 image length.

**Comment by khushpreet-kaur** [comment]
@salus-sage  Resolved.  Please review.
