### ISSUE TITLE
collbrations - first image in firefox not coming properly.

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#37]

**Comment by salus-sage** [comment]
image problem tested in Firefox version 49.0.2 - no obvious problem, needs more description

**Comment by khushpreet-kaur** [comment]
@salus-sage  @pradyumnat  Tested on Firefox 49.0 / 47.0- Image is loading fine. No such issue occurred while testing.

**Comment by salus-sage** [comment]
tested and confirmed - no issue such as image not displaying properly, other loading issues with firefox will be addressed in issue #36
