### ISSUE TITLE
mentorship - first audio has some sound and not clearly audible.

### ISSUE THREAD

**Issue by pradyumnat** [janastu/ncbs-omeka-backbone-client#43]

**Comment by salus-sage** [comment]
need to check the volume with the original video. @shalinia can you please assign this issue to somebody from the content production team to check the sound in original video and the web version and see if anything can be done to resolve this issue.

**Comment by shalinia** [comment]
The first audio has page flipping sound. I think the recorder was kept closer to the book. Otherwise there are no noise in the audio file. https://www.ncbs.res.in/ncbs25/omeka/files/original/c281a0f1fc34267fabc9433d991bfcb8.mp3

**Comment by salus-sage** [comment]
the noise and audio volumes is out of scope of work for us. this issue will be closed as resolved.
