### ISSUE TITLE
Gallery should be collapsible

### ISSUE THREAD

**Issue by salus-sage** [janastu/ncbs-omeka-backbone-client#47]

**Comment by vns2** [comment]
@salus-sage Is this the same as the old request to have gallery as a simple box at the bottom marked 'Gallery'. And clicking the 'Gallery' box just opens a file list with all gallery items on a new page. That's the full extent of the Gallery requirement. Thanks!

**Comment by salus-sage** [comment]
yes - the full scope of gallery requirements is addressed in issues #47 #49 #53 
and we are working it to make a hidden gallery, which will show up on button click. rather than a new page.  this is how it looks so far. 

before button click
![collapsed-before-button-click](https://cloud.githubusercontent.com/assets/6399323/19771450/9e044fb8-9c80-11e6-8cb3-b19e852d888a.png)

after button click
![expanded-after-button-click](https://cloud.githubusercontent.com/assets/6399323/19771449/9dfce7f0-9c80-11e6-8e1b-ffc488c6cf5d.png)

**Comment by vns2** [comment]
Lovely! I like your hidden gallery idea. It looks great. I don't know about colour scheme, what goes with what, etc. If you're in touch with designers, maybe they can give you an idea. But it's fine for beta release, I think.

**Comment by salus-sage** [comment]
i thought we'll finish the technical components required with basic colors and icons, and once we have a stable release, i would ask for the designers input for changes. Hope thats fine.
