### ISSUE TITLE
Enter theme at curatorial note; add distinguishing factor for curatorial note tab from other chapter tabs;

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#52]
Just inserting the auth/curatorial note comment from Dinesh's email as an issue on git. I am fine with starting theme on curatorial note. However, we do need to distinguish the note in some way from the other chapters.

**Comment by salus-sage** [comment]
separating the  issue from  add dummy pixel to tab to enable authorization -> which will be handled under the refactor issue
