### ISSUE TITLE
Chrome v54: Audio, pics not loading

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#56]
Omeka content does not appear to load in Chrome v54, even after waiting for a while. In some themes, it loads, but not all the time. Quite often, clicking the audio button doesn't result in starting of the audio file. (Content loads okay in Firefox v48 after waiting for ~5-6 seconds).

**Comment by salus-sage** [comment]
issue resolved, chrome loading is optimized and confirmed by testing. changes are live.
