### ISSUE TITLE
Chrome: Gallery in new tab-No content- For all themes

### ISSUE THREAD

**Issue by nikithag19** [janastu/ncbs-omeka-backbone-client#58]
When Gallery is opened in a new tab the content overlaps the logo showing no media files. 

![image](https://cloud.githubusercontent.com/assets/16652447/19962452/ad194b4a-a1dd-11e6-978e-dd1f8b9c8d56.png)

**Comment by salus-sage** [comment]
the gallery is not supposed to be opened in a new tab, its a popout content box, and not another route. This issue is invalid

**Comment by salus-sage** [comment]
reference issue #47
