### ISSUE TITLE
Chrome: Peopleplex nodes not displayed

### ISSUE THREAD

**Issue by nikithag19** [janastu/ncbs-omeka-backbone-client#62]
The audio nodes doesn't appear.

![image](https://cloud.githubusercontent.com/assets/16652447/20061396/b61967ca-a525-11e6-9de6-6cf8573ffd4c.png)

**Comment by khushpreet-kaur** [comment]
@nikithag19 I tried in many different scenarios, it seems to work. Can you check your browser console for errors?

**Comment by nikithag19** [comment]
It seems to be working now. But yesterday when i tried it appeared as attached in screenshot.  When i checked on browser console, it showed few java script errors.
