### ISSUE TITLE
Chrome v54: Peopleplex - "dead" nodes on top row + missing names

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#68]
I found the following nodes as shown in attached image (top row, four nodes) to be dead in Chrome v54, and possibly any other browser. The 'content' hidden changes as you click on different nodes -- the toroid rotates slightly, usually clockwise.

In addition, whatever I do, I am not able to get the content for three people in any config:
Obaid Siddiqi (should be near nodes of Zakir Hussain and Riayat Khan)
Umashashi (should be near Meena Srinivasan and Shaju Varghese)
T Eswar (should be near GH Mohan and SN Basha).

![chrome_peopleplex_nodes-not-working](https://cloud.githubusercontent.com/assets/4581081/20376009/25c1a4b8-aca9-11e6-8754-417be8e1d4d9.png)

**Comment by vns2** [comment]
@salus-sage I think I can see the source of the problem. It is driven by the top 'ncbs25' bar. In any browser window size, any node above that bar will not be clickable. If I go to a smaller screen, more nodes become dead, but always above a 'horizontal' line. Can you just move the toroid down by an inch or how much ever is possible maximum. That should fix it, I think.

**Comment by salus-sage** [comment]
Issue resolved and changes are live.
