### ISSUE TITLE
Access password: Becoming required even while within the NCBS IP system

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#69]
The NCBS@25 site is asking for a username and password even while within the NCBS IP system for some logins. Not sure why. This was tested on Chrome v54 and Firefox with two different users inside NCBS.

**Comment by arunk** [comment]
Can you get the IP addresses from which these users are accessing the system?

**Comment by vns2** [comment]
@arunk 172.16.110.193 is my private IP (I get asked for authentication as well), and I believe others will have a similar IP address. I spoke to Rajesh -- he said he will said the private IP address range to you guys so you can include it in your authentication clearance.

**Comment by arunk** [comment]
@vns2 can you go here - http://www.whatsmyip.org/ and tell me the IP address that you see?

**Comment by vns2** [comment]
Resolved. Thanks!
