### ISSUE TITLE
Photo slideshow: Zoom icon?

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#73]
Is it possible to have some sort of a magnifying glass icon or some way to illustrate how to zoom into photos in the slideshow, whenever the mouse hovers over the image? Or maybe on the side of the slideshow... 

Have now had a few people comment on not being able to see the content in the photos and not many seem to intuitively use the mouse scroll or touchpad squeeze option to zoom and see it.

**Comment by salus-sage** [comment]
Issue resolved - fix committed and live
