### ISSUE TITLE
Home page text revision

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#74]
@salus-sage Having put more thought into this, I think it will be better for the website home page to have tweak of a few words. Can you please use the attached text in the homepage box?
Many thanks!
Venkat

***

**Thirteen ways of looking at NCBS**

On Oct 22, 1991, the Department of Atomic Energy sent a letter to the Tata Institute for Fundamental Research. It conveyed the President's sanction for a new biology research centre in Bangalore. It stands as a bookend of sorts to a decade-plus process.

The National Centre for Biological Sciences (NCBS) completes 25 years this year. The NCBS@25 exhibit is built around thirteen ways to reflect upon the history of the institution. Browse the seven story themes below (better viewed in sequence). And explore the six widgets under the Sandbox icon including a Timeline and other experimental archival tools.

In history-writing, stories sometimes surface by bestowing significance on available material. Even chipping off a wall, as seen on the right, can take upon an intriguing new life of its own. The exhibit celebrates such multiple interpretations. It brings to light the tapestry of NCBS, weaved by over 70 story tellers. Along with over 600 photographs, official records, letters, and the occasional lab note, they allow a glimpse into a tangled history and unlikely journey.

**Comment by salus-sage** [comment]
Text updated, however need more clarification.
@vns2 do you need this heading "Thirteen ways of looking at NCBS"

**Comment by salus-sage** [comment]
Issue resolved, pushed text with the heading as-is

**Comment by vns2** [comment]
@salus-sage Yes, would like the heading in this rev. I reduced the text accordingly. Does it work?

**Comment by salus-sage** [comment]
Sure, it works. i have the heading also, changes are live, you can have a
look and confirm.
