### ISSUE TITLE
Peopleplex: Not working on Internet Explorer

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#76]
Peopleplex does not work on Internet Explorer. (Tested on IE version 11). It works on Chrome, Firefox and Edge.

**Comment by salus-sage** [comment]
Solution - code error from console fixed and pushed - awaiting for changes to go live on server
Limitations and requirements:
SVG and D3 transitions are not supported in IE 8 and below.
Hence the animation is slow and different compared to other browsers
See below links for more info:
http://caniuse.com/#feat=svg
http://stackoverflow.com/questions/15159002/d3-js-browser-support
However IE9 and above Edge should work. 
tested IE11 and edge - test passed
