### ISSUE TITLE
SpaceTour: Internet Explorer not working 

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#77]
SpaceTour loads on Internet Explorer (tested on version 11) but it does not work -- no rotation, clicking capability. It works fine on Chrome, Firefox, Edge.

**Comment by salus-sage** [comment]
only latest and modern browsers support the webGL and 3d features like firefox and chrome V49 onwards,
IE11 onwards. for more info. visit http://caniuse.com/#feat=webgl
The actual error from console is 
Object doesn't support property or method 'sign'
no alternative from msdn docs
https://msdn.microsoft.com/en-us/library/mt146833(v=vs.94).aspx
Supported only in Edge browser
This issue will be closed marking "invalid " "wontfix"

**Comment by salus-sage** [comment]
@pradyumna suggested a fallback message if an user opens space tour in IE, a message will appear saying this is best experience in chrome and firefox V49 and upwards

**Comment by pradyumnat** [comment]
https://github.com/janastu/ncbs-space-tour/commit/9887e7cd7ae4384e0c68b1c73b0c6ff9ca28b794

**Comment by salus-sage** [comment]
Changes are live - Added an alert box if user access space tour in Internet explorer to reroute to chorme or firefox.
