### ISSUE TITLE
NCBS@25 Favicon

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#81]
Feedback from NCBS beta tester:

The NCBS@25 favicon is not visible when on the page. It only becomes visible when you are on a different tab. And its scaling is off.

One solution could be to colour it black, and resize/crop for favicon to make it a square?

**Comment by salus-sage** [comment]
replace favicon to a square 10x10 image with a contrasting color. will assign to nikitha to modify the logo image and mark milestone 1.0.1

**Comment by salus-sage** [comment]
nikitha has sent this favicon, will be pushed to server shortly.
![ncbs_favicon](https://cloud.githubusercontent.com/assets/6399323/20710724/bb8099de-b661-11e6-9f93-a0ce2051bb09.png)

**Comment by vns2** [comment]
Great!

**Comment by vns2** [comment]
Seen, looks nice! Resolved.
