### ISSUE TITLE
Identity theme - Space for Biology chapter - move Audio icon

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#82]
Move the audio file to the stated location. This was supposed to be an audio slideshow. But if this is not happening in this version, then we need to move the audio file soon after the sentence. Else, it looks out of place.

![identity-space-swami-play](https://cloud.githubusercontent.com/assets/4581081/20558415/e19a0d24-b195-11e6-9168-03ac50e89aed.png)

**Comment by salus-sage** [comment]
Hi @vns2  for this you have to update the content in omekat. the tag A1 should come before the tag PS1. I assume you can do these changes in content. 
Hence marking this as "wontfix" and will close the issue after you fix the content on omeka. Let me know if you need the login credentials.

**Comment by vns2** [comment]
Yes, I could. But I forgot the login credentials :( what is it?

**Comment by vns2** [comment]
Fixed.
