### ISSUE TITLE
Research theme - Queries and tools chapter - Very low res photo

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#84]
The first featured photo of glass blowing is of very low res and very pixelated in the compressed form. Unable to see. Can this be re-uploaded with a decent resolution?
Thanks!

**Comment by salus-sage** [comment]
@vns2 the solution for this issue is similar to issue #82 you can replace the photograph in omeka with the picture of your choice. 
p.s. find the item in question - > delete the existing picture and upload a new picture

**Comment by vns2** [comment]
Fixed.
