### ISSUE TITLE
Research theme - Queries and tools chapter - Slideshow - Very low res photos

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#85]
Photos 1,12,13 in the picture slideshow of this chapter are very low res and pixelated. Can they be re-uploaded with better quality?
Thanks!

**Comment by salus-sage** [comment]
@vns2 solution similar to issue #84 please replace the pictures. marking this as "wontfix" too

**Comment by vns2** [comment]
Fixed.
