### ISSUE TITLE
Research theme - Processes chapter - Slideshow image #9 rotate

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#86]
Make Image 9 in processes chapter of research theme in portrait mode (instead of current setup in landscape)

**Comment by salus-sage** [comment]
This seems to be a bug - the original image at https://www.ncbs.res.in/ncbs25/omeka/files/original/147cc0f51d9aa4a1b749b61bc521280c.jpg
https://www.ncbs.res.in/ncbs25/omeka/admin/files/show/781 but here in thumbnail mode the photo is rotated
 is in landscape mode, however the one rendered in slide show is rotated. should look into this

Solution: to re-upload the image after rotating in photoshop.

**Comment by vns2** [comment]
Fixed with re-uploaded image.
