### ISSUE TITLE
Identity theme - Science in india chapter - Photo slideshow (last) - low res photo

### ISSUE THREAD

**Issue by vns2** [janastu/ncbs-omeka-backbone-client#87]
Image 1 in the last photo slideshow of Science in India chapter (identity theme) is very low res and pixelated. Can't read. Can this be re-uploaded in higher res?
Thanks!

**Comment by salus-sage** [comment]
@vns2 solution similar to issue #84  marking this as "wontfix"

**Comment by vns2** [comment]
Resolved.
